package videoserver

const (
	SCOPE_APP           = "app"
	SCOPE_CONFIGURATION = "configuration"
	SCOPE_STREAM        = "stream"
	SCOPE_STREAMING     = "streaming"
	SCOPE_WS_HANDLER    = "ws_handler"
	SCOPE_API_SERVER    = "api_server"
	SCOPE_WS_SERVER     = "ws_server"
	SCOPE_ARCHIVE       = "archive"
	SCOPE_MP4           = "mp4"
	SCOPE_HLS           = "hls"

	EVENT_APP_CORS_CONFIG = "app_cors_config"

	EVENT_STREAM_CODEC_ADD     = "stream_codec_add"
	EVENT_STREAM_STATUS_UPDATE = "stream_status_update"
	EVENT_STREAM_CLIENT_ADD    = "stream_client_add"
	EVENT_STREAM_CLIENT_DELETE = "stream_client_delete"
	EVENT_STREAM_CAST_PACKET   = "stream_cast"

	EVENT_STREAMING_RUN                 = "streaming_run"
	EVENT_STREAMING_START               = "streaming_start"
	EVENT_STREAMING_DONE                = "streaming_done"
	EVENT_STREAMING_RESTART             = "streaming_restart"
	EVENT_STREAMING_DIAL                = "streaming_dial"
	EVENT_STREAMING_STATUS_UPDATE       = "streaming_status_update"
	EVENT_STREAMING_PACKET_SIGNAL       = "streaming_packet_signal"
	EVENT_STREAMING_STOP_SIGNAL         = "streaming_stop_signal"
	EVENT_STREAMING_CODEC_UPDATE_SIGNAL = "streaming_codec_update_signal"
	EVENT_STREAMING_EXIT_SIGNAL         = "streaming_codec_exit_signal"
	EVENT_STREAMING_CODEC_MET           = "streaming_codec_met"
	EVENT_STREAMING_AUDIO_MET           = "streaming_audio_met"
	EVENT_STREAMING_HLS_CAST            = "streaming_hls_cast"
	EVENT_STREAMING_MP4_CAST            = "streaming_mp4_cast"

	EVENT_API_PREPARE     = "api_server_prepare"
	EVENT_API_START       = "api_server_start"
	EVENT_API_CORS_ENABLE = "api_server_cors_enable"
	EVENT_API_REQUEST     = "api_request"

	EVENT_WS_PREPARE     = "ws_server_prepare"
	EVENT_WS_START       = "ws_server_start"
	EVENT_WS_CORS_ENABLE = "ws_server_cors_enable"
	EVENT_WS_REQUEST     = "ws_request"
	EVENT_WS_UPGRADER    = "ws_upgrader"
	EVENT_WS_PING        = "ws_ping"

	EVENT_HLS_START_CAST              = "hls_start_cast"
	EVENT_HLS_PLAYLIST_PREPARE        = "hls_playlist_prepare"
	EVENT_HLS_PLAYLIST_CREATE         = "hls_playlist_create"
	EVENT_HLS_PLAYLIST_RESTART        = "hls_playlist_restart"
	EVENT_HLS_CLOSE_FILE              = "hls_close_file"
	EVENT_HLS_WRITE_TRAIL             = "hls_write_trail"
	EVENT_HLS_REMOVE_OUTDATED         = "hls_remove_outdated"
	EVENT_HLS_REMOVE_OUTDATED_SEGMENT = "hls_remove_outdated_segment"
	EVENT_HLS_REMOVE_CHUNK            = "hls_remove_chunk"

	EVENT_ARCHIVE_START_CAST  = "archive_start_cast"
	EVENT_ARCHIVE_CREATE_FILE = "archive_create_file"
	EVENT_ARCHIVE_CLOSE_FILE  = "archive_close_file"
	EVENT_CHAN_PACKET         = "mp4_chan_pck"
	EVENT_CHAN_STOP           = "mp4_chan_stop"
	EVENT_CHAN_KEYFRAME       = "mp4_chan_keyframe"
	EVENT_SEGMENT_CUT         = "mp4_segment_cut"
	EVENT_NO_START            = "mp4_no_start"
	EVENT_MP4_WRITE           = "mp4_write"
	EVENT_MP4_WRITE_TRAIL     = "mp4_write_trail"
	EVENT_MP4_SAVE_MINIO      = "mp4_save_minio"
	EVENT_MP4_CLOSE           = "mp4_close"
)
